# this configuration file has all empty custom components set up.
# use 'esphome test_empty.yaml compile' to build.

external_components:
  - source: components

packages:
  device: !include device.yaml # include our test device setup

sensor:
  - platform: mmwave
    name: mmwave sensor