esphome:
  name: mmwave3
  friendly_name: mmwave3

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERY_VERBOSE
  baud_rate: 115200

debug:
  update_interval: 5s 

text_sensor:
  - platform: debug
    device:
      name: "Device Info" 
    reset_reason:
      name: "Reset Reason"

# Enable Home Assistant API
api:
  encryption:
    key: "1EpoxpVwhtgP4qD9aY3Kd5oU8n7zeEu2nHBH/EFa5do="

ota:
  - platform: esphome
    password: "cd956dd0b4435322ffd35f278b42a386"

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mmwave3 Fallback Hotspot"
    password: "uJ9kqXhYNoND"

captive_portal:
    
external_components:
  - source: components

uart:
  id: uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 115200  

mmwave:
  id: mmwave_component
  uart_id: uart_bus
  packet_text_sensor_id:
    id: mmwave_packets_text_sensor
    name: "MMWave Packets"
  movement_sensor_id:
    id: mmwave_movement_sensor
    name: "Movement Rate"
  
button:
  - platform: template
    name: "MMWave Control"
    id: mmwave_control_btn 
    on_press: 
      then:
        - lambda: |-
            id(mmwave_component).send_command();

  - platform: template
    name: "Send Sleep Command"
    id: sleep_command_btn 
    on_press: 
      then:
        - lambda: |-
            id(mmwave_component).send_sleep_mode_command();

